### PR TITLE
fixed some PEP 8 issues

### PR DESCRIPTION
**Pull request by AjmalPonneth**

### CODE REVIEW

**Review by buckydevv — APPROVED** [review]
Thank you!

**Comment by AjmalPonneth** [comment]
@buckydevv Yo! Wassup 🔥

**Comment by buckydevv** [comment]
wasssup mannnnn!!!!

**Comment by buckydevv** [comment]
wassup! been years

**Review by buckydevv — COMMENTED** [review]
thank you!

**Comment by buckydevv** [comment]
> @buckydevv Yo! Wassup 🔥

add me on discord

**Comment by AjmalPonneth** [comment]
@buckydevv then, please share your discord here.

**Pull request merged**
